apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox-echo
  name: busybox-echo
spec:
  containers:
  - image: busybox
    name: busybox-echo
    command: ['sh', '-c', 'echo "The BEST DevOps COURSE!!!" && sleep 3600']
