apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-application
  name: flask-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-application
  template:
    metadata:
      labels:
        app: flask-application
    spec:
      containers:
      - image: nvrbckdown/flask-app:last-practice
        name: flask-app
        resources: 
          limits:
            cpu: 150m
            memory: 128Mi
          requests:
            cpu: 75m
            memory: 64Mi

