apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: flask-application-network-policy
spec:
  podSelector:
    matchLabels:
      app: flask-application
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kuber: admin

