apiVersion: batch/v1
kind: CronJob
metadata:
  name: node-printer
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      completions: 10
      parallelism: 5
      template:
        spec:
          containers:
            - name: node-printer
              image: nginx
              imagePullPolicy: IfNotPresent
              env: 
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
              command:
                - /bin/sh
                - -c
                - echo $NODE_NAME

          restartPolicy: OnFailure
